version: "3"

services:
  web:
    build: .
    container_name: "Django-server"
    # command: python manage.py runserver
    # volumes:
    #   - .:/app/
    ports:
      - 8000:8000

  # db:
  #   image: postgres:13.0-alpine
  #   container_name: "postgres-db-server"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
