# Generated by Django 4.1.2 on 2022-10-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='owner',
            field=models.TextField(),
        ),
    ]
